Первая попытка после создания нового репозитория
SharkWD/todolist pull request #1
Opened 2024-06-03 18:10 UTC by SharkWD

2024-06-03 19:18 UTC, just-musha requested changes
Супер, теперь все изменения видны. Оставляю коменты по 1 итерации - самое главное - нужно проверить и залогировать ошибку от Write, остальное не крит.

2024-06-03 19:18 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Это внутренняя ошибка сервера

2024-06-03 19:18 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Этот метод возвращает 2 значения, одно из которых ошибка. Её нужно явно обработать - и в данном случае достаточно её просто залогировать.

2024-06-03 19:18 UTC, just-musha commented on precode.go
> +	w.Write(resp)
И здесь

2024-06-03 19:18 UTC, just-musha commented on precode.go
> +	tasks[task.ID] = task
Если такой айди уже есть, то задача перезатрется. Лучше проверить - и если есть, то вернуть ошибку пользователю

2024-06-03 19:25 UTC, SharkWD commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
А что не так, не пойму. В задании написано, что в случае ошибки вернуть 400 Bad Request

2024-06-03 19:55 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Отправлю авторам задания, спасибо!

По логике. бэд реквест - это когда что-то не то пользователь передал. А здесь мы не смогли сформировать json - и это уже проблема сервера, пользователь ни при чем

2024-06-03 19:58 UTC, just-musha requested changes
Ещё пара моментов

2024-06-03 19:58 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Нужно именно залогировать

Возвращать пользователю ошибку не нужно, тк http.Error тоже под капотом внутри вызовет Write, а с ним уже проблема выше. Записать не получится скорее всего

2024-06-03 19:58 UTC, just-musha commented on precode.go
> +		http.Error(w, "Такая задача уже есть в списке дел", http.StatusBadRequest)
Супер

2024-06-03 19:58 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Тоже залогировать, не нужно возвращать пользователю

2024-06-03 20:01 UTC, SharkWD commented on precode.go
> +		http.Error(w, "Такая задача уже есть в списке дел", http.StatusBadRequest)
Тогда подскажите, пожалуйста, как это реализовать. Не совсем понимаю логирование ошибок ((

2024-06-03 20:02 UTC, SharkWD commented on precode.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Тогда подскажите, пожалуйста, как это реализовать. Не совсем понимаю, как залогировать ошибки ((

2024-06-04 09:26 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Я к сожалению не отслеживаю комментарии, пока работа не придет на ревью, работ оч много :)

Сейчас вижу что удалось разобраться! Отлично :+1:

2024-06-04 09:32 UTC, just-musha requested changes
Принцип вывода в лог - все верно. Доведем до идеала само сообщение об ошибке?

2024-06-04 09:32 UTC, just-musha commented on precode.go
> +		fmt.Printf("Ошибка сервера: %v", http.StatusInternalServerError)
Сейчас в лог запишется так: `Ошибка сервера: 500`. Хочется иметь большше информации, чтоб мы по логу смогли понять  что конкретно там пошло не так

Поэтому здесь лучше запиисать саму ошибку `err` и сообщение - что-то вроде "ошибка при записи ответа".

2024-06-04 10:47 UTC, just-musha approved these changes
Все верно! Надеюсь было полезно и удалось в процессе разобраться. Работа принята! Успехов дальше на курсе!
![image](https://github.com/SharkWD/todolist/assets/23293688/4f1b9273-dfaa-48b8-b98e-4e0122cecd7f)

2024-06-15 16:11 UTC, merged